### ISSUE TITLE
Delays related to Key and No Gear modes

### ISSUE THREAD

**Issue by tflo** [TheMouseNest/PointBlankSniper#15]
This is the continuation of a side thing of a closed [thread](https://github.com/Auctionator/PointBlankSniper/issues/13#issuecomment-1683962975):

> As a side note: The Keys and No gear modes expose a delay when going back from the Shopping tab to the Sniper tab. I haven't payed attention if it always was like that, or if this is normal. (In Blank mode, there is no delay.)

That's how I get these delays:

1. Set PBS mode to _Keys_ or to _No gear_
2. Reload UI
3. Wait 15s or so, until client/addons have done their loading duties
4. Right-click the single most important NPC of this game (Auctioneer O'reely)
5. Click Sniping tab

--> Delay(stalling) for approx. 4 seconds, sometimes the OS's "busy" cursor comes up

I can repeat steps 4–5 in the same session, and I always get the delay. Is this the "Do search information preprocessing needed for keys search" setting? (But this setting is de facto unchangeable, because you get a reminder popup if you disable it and are in one of the modes it refers to.)

In Blank mode, there isn't any delay.

Now the even more interesting, and probably really buggy part:

When doing the steps as outlined above, or only steps 4–5, I often get a delay also already when clicking O'reely (i.e. opening the AH frame).

This happens always _at least_ if I had closed the AH frame from within the PBS tab. For example, if I close the AH frame from within the Selling tab, or any of Blizz's tabs, it doesn't happen.

This feels as if PBS was doing its "information preprocessing" twice (if it is that): when opening the AH frame, and again when activating the PBS tab.

---

Edit: Changed some semantically significant 'when' to 'if'.

**Comment by plusmouse** [comment]
When using the keys mode (and hence have also enabled search information preprocessing to get it to work) it is normal when opening the sniping tab for the first time after a login or reload to get a very noticeable delay.

This delay comes from parsing the precomputed names for use with the keys search. Actually computing the names takes even longer which is why they are precomputed.

The additional delay when swapping tabs happens when additional processing takes place to recall which item keys have been seen and which haven't to detect new keys. If this processing is interrupted it then starts again, causing the lag.

**Comment by plusmouse** [comment]
I've pushed a fix that should prevent the lag from repeating after the initial tab opening.

**Comment by plusmouse** [comment]
[PointBlankSniper-5.33-2-g7b9fa77.zip](https://github.com/Auctionator/PointBlankSniper/files/12383053/PointBlankSniper-5.33-2-g7b9fa77.zip)

**Comment by tflo** [comment]
> I've pushed a fix that should prevent the lag from repeating after the initial tab opening.

That would be great. Will test the patch later (soon).

**Comment by tflo** [comment]
Still the same, sorry. Opening the AH frame should not produce a delay, as i already will get the delay once I open the PBS tab.  It seems your caching scope does not cover everything it should. (Or is not seen by the sniping function)(s))

**Comment by plusmouse** [comment]
I can't replicate a delay when opening the AH frame. Are you sure that this delay is caused by PBS?

**Comment by tflo** [comment]
> Are you sure that this delay is caused by PBS?

Just testing it without any other addon, so yes.

Some additional infos that might be important:

(With "the issue", I'm referring to the delay when opening the AH frame.)

- My default tab is set to the "Selling" tab.
- The issue does not occur immediately after a reload.
- The issue only occurs if PBS mode is set to Keys or No Gear.
- The issue does not occur next time, if you close the AH _not_ from within the Sniping tab.

The last point here makes me think now that something like this is happening _when reopening_ the AH frame: Auctionator is opening to the Sniper tab (which was the last open tab), which results in the first delay due to the info proprocessing --> Before the PBS tab gets visible, Auctionator "realizes" that the default tab is set to the Selling tab --> It opens to the Selling tab --> I switch manually to the Sniper tab and get the preprocessing delay once again with that.

Here the detailed steps to reproduce:

Preparation:
1. Set PBS to Keys mode. Make sure your Auctionator default tab is "Selling".
2. Reload UI (optionally with everything disabled except your addon manager, Auctionator, and PBS).
3. After the reload, open the AH frame (probably you will not get any delay).
4. Switch to PBS tab (probably delay here).
5. Close the AH frame from within PBS ("from within PBS" = close it while PBS is the active tab).

Now, I can endlessly repeat this:

1. Open AH frame
    - I get the first delay here
2. Switch from Selling tab to PBS tab
    - I get the second delay here
3. Close AH frame (from within PBS tab), repeat from step 1


Both delays seem to be of approx. the same duration. I'm assuming that both delays are caused by the "information preprocessing", but this is not really important from a user's point; my point is that there _should_ only be the delay when actually opening the PBS tab (i.e. the one that I called "second delay" in the steps above.


Versions, as copied from toc:
Autionator: 10.1.17-1-g65c7c80
PBS: 5.33-2-g7b9fa77

WoW version:
10.1.5.50791

**Comment by plusmouse** [comment]
This should resolve that issue:
[PointBlankSniper-5.33-3-ga6a2f9f.zip](https://github.com/Auctionator/PointBlankSniper/files/12395760/PointBlankSniper-5.33-3-ga6a2f9f.zip)

**Comment by plusmouse** [comment]
(Its a "feature" of the AH, both Blizzard and non-Blizzard tabs will be reshown for an instant when reopening the AH even if they're not the default). Fixed the issue by hiding the Sniping tab a second time so it doesn't count as shown even temporarily when the AH is opened.

**Comment by tflo** [comment]
Bingo, looks like you did it 🥳

> Its a "feature" of the AH, both Blizzard and non-Blizzard tabs will be reshown for an instant when reopening

Seems I wasn't too far off with my guess then. I love those _features_ 🫨

Thanks!


---


A quick question, if you don't mind:

I mainly (ab)use the PBS as a quick list generator for cheap pets (60% or so of DBRegionMarketAvg). Is it correct that Blank mode is the best mode for that? (which is what I am normally using)

**Comment by plusmouse** [comment]
Blank is fine. Keys is only if you're trying to compete with faster moving items (either because they sell a lot or another sniper is competing).

**Comment by tflo** [comment]
Good info on Keys mode. Thank you.
